import {spawn} from 'node:child_process';
import {mkdtemp,writeFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,dirname,basename} from 'node:path';
const root='D:/syh_code/CDC/app/prototypes/web-ui';
const out=join(root,'qa');
await mkdir(out,{recursive:true});
const profile=await mkdtemp(join(tmpdir(),'cdc-ui-qa-'));
if(dirname(resolve(profile))!==resolve(tmpdir())||!basename(profile).startsWith('cdc-ui-qa-'))throw new Error('Unexpected browser profile path');
const port=9333;
const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-allow-origins=*','--remote-debugging-port='+port,'--user-data-dir='+profile,'about:blank'],{windowsHide:true,stdio:'ignore'});
let ws;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const checks=[],errors=[];
function assert(ok,name){checks.push({name,pass:!!ok});if(!ok)throw new Error(name);}
try{
 let tabs;
 for(let i=0;i<70;i++){try{tabs=await (await fetch('http://127.0.0.1:'+port+'/json')).json();break;}catch{await pause(200);}}
 if(!tabs)throw new Error('Chrome debug endpoint unavailable');
 ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);
 await new Promise((res,rej)=>{ws.onopen=res;ws.onerror=rej;});
 let seq=0;const pending=new Map();
 ws.onmessage=e=>{const data=JSON.parse(e.data);if(data.id){const cb=pending.get(data.id);if(cb){pending.delete(data.id);clearTimeout(cb.timer);data.error?cb.reject(new Error(JSON.stringify(data.error))):cb.resolve(data.result);}}
 else if(data.method==='Runtime.exceptionThrown')errors.push(data.params.exceptionDetails.text+' '+(data.params.exceptionDetails.exception?.description||''));
 else if(data.method==='Log.entryAdded'&&data.params.entry.level==='error')errors.push(data.params.entry.text);};
 const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout '+method));},12000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
 const wait=async expression=>{for(let i=0;i<50;i++){if(await evaluate(expression))return;await pause(80);}throw new Error('Wait failed: '+expression);};
 const click=selector=>evaluate('document.querySelector('+JSON.stringify(selector)+').click()');
 const input=(selector,value,event='input')=>evaluate('(()=>{const el=document.querySelector('+JSON.stringify(selector)+');el.value='+JSON.stringify(value)+';el.dispatchEvent(new Event('+JSON.stringify(event)+',{bubbles:true}));})()');
 const text=selector=>evaluate('document.querySelector('+JSON.stringify(selector)+').innerText');
 const go=async path=>{await evaluate('location.hash='+JSON.stringify(path));await pause(100);};
 const screen=async(name,width=1440,height=1024)=>{await cdp('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});await evaluate('document.fonts.ready');await pause(120);const r=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(join(out,name+'.png'),Buffer.from(r.data,'base64'));};
 await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Log.enable');
 await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1024,deviceScaleFactor:1,mobile:false});
 await cdp('Page.navigate',{url:'http://127.0.0.1:4173/index.html#detail/task_users'});
 await wait('document.readyState==="complete" && !!document.querySelector("#password")');
 assert(await evaluate('!document.querySelector("#login").classList.contains("hidden")&&document.querySelector("#app").classList.contains("hidden")'),'Direct task URL shows demo login when signed out');
 await screen('login');
 await input('#password','wrong');await click('#login-form button');
 assert((await text('#login-error')).includes('错误'),'Wrong password shows inline error');
 await input('#password','cdc-demo');await click('#login-form button');
 await wait('document.querySelector("#page-detail").classList.contains("active")');
 assert((await text('#detail-content')).includes('用户中心同步'),'Login preserves task deep link');
 assert((await text('#mapping-trees')).includes('user_profiles')&&!(await text('#mapping-trees')).includes('orders'),'Users task has its own tables');
 assert((await text('#log-content')).includes('19006')&&!(await text('#log-content')).includes('18294'),'Users task has its own transaction logs');
 await click('[data-log-kind="error"]');
 assert((await text('#log-content')).includes('没有错误日志'),'Users error tab has a real empty state');
 await screen('detail-users');
 await go('home');
 assert(await evaluate('document.querySelectorAll("#instance-rows tr").length===3'),'Home lists all three instances');
 assert(await evaluate('document.querySelector("#page-home .route-topology")===null'),'Home has no single-task topology');
 assert((await text('#instance-rows')).includes('源端 / 目的端'),'8.0 instance can have both roles');
 assert(await evaluate('document.querySelectorAll("#page-home [data-page=add],#page-tasks [data-page=add]").length===0'),'No duplicate add-task buttons on home or task list');
 await click('button[data-instance="target80"]');
 assert((await text('#instance-inspector')).includes('作为源端')&&(await text('#instance-inspector')).includes('作为目的端'),'Inspector derives each associated task role');
 await screen('home-dark');
 assert(await evaluate('getComputedStyle(document.querySelector("#menu")).display==="none"'),'Desktop hides mobile navigation toggle');
 await click('[data-instance-tasks="target80"]');await pause(100);
 assert(await evaluate('document.querySelectorAll("#task-rows tr").length===2'),'Instance link filters task list');
 assert((await text('#task-rows')).includes('库存归档')&&!(await text('#task-rows')).includes('订单实时同步'),'Associated list contains the correct routes');
 await click('#clear-task-filter');
 assert(await evaluate('document.querySelectorAll("#task-rows tr").length===4'),'Clear filter restores all tasks');
 await screen('tasks');
 await click('#task-rows button[data-route="task_orders_prod"]');await pause(100);
 assert((await text('#endpoint-layout')).includes('mysql-source-57')&&(await text('#endpoint-layout')).includes('mysql-target-84'),'Order detail shows 5.7 to 8.4');
 assert((await text('#mapping-trees')).includes('orders')&&!(await text('#mapping-trees')).includes('user_profiles'),'Order detail does not reuse users mapping');
 await click('[data-endpoint="sink"]');
 assert((await text('#detail-inspector')).includes('目的端实例')&&(await text('#detail-inspector')).includes('MySQL 8.4'),'Selecting endpoint updates configuration inspector');
 await click('[data-table="payments"]');
 assert(await evaluate('document.querySelectorAll("[data-table=payments][aria-pressed=true]").length===2'),'Selecting a table highlights both sides');
 await screen('detail-orders');
 await click('[data-log-kind="error"]');
 assert((await text('#log-content')).includes('已回滚')&&!(await text('#log-content')).includes('已提交'),'Error tab filters order rollback');
 await click('[data-log-kind="runtime"]');
 assert((await text('#log-content')).includes('连接恢复')&&!(await text('#log-content')).includes('18294'),'Runtime tab filters connection events');
 await evaluate('document.querySelector("#tab-runtime").dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true}))');
 assert(await evaluate('document.activeElement.id==="tab-error"&&document.querySelector("#tab-error").getAttribute("aria-selected")==="true"'),'Log tabs support keyboard selection');
 await click('#pause-route');assert((await text('#global-status')).includes('1 个任务运行'),'Pause updates global mock count');
 await click('#pause-route');assert((await text('#global-status')).includes('2 个任务运行'),'Resume restores global mock count');
 await input('#task-switch','task_inventory','change');await pause(100);
 assert((await text('#endpoint-layout')).includes('mysql-target-80')&&!(await text('#endpoint-layout')).includes('mysql-source-57'),'Switching to inventory uses 8.0 source');
 assert((await text('#mapping-trees')).includes('stock_movements')&&!(await text('#mapping-trees')).includes('payments'),'Inventory has independent mappings');
 assert((await text('#log-content')).includes('binlog.000009:8421'),'Inventory has independent file-position logs');
 await screen('detail-inventory');
 await cdp('Page.reload');await wait('document.readyState==="complete"&&document.querySelector("#detail-content")?.innerText.includes("库存归档")');
 assert((await text('#detail-content')).includes('库存归档'),'Reload keeps selected task');
 await go('tasks');await evaluate('history.back()');await pause(150);
 assert((await text('#detail-content')).includes('库存归档')&&await evaluate('document.querySelector("#page-detail").classList.contains("active")'),'Browser back restores selected task');
 await go('detail/missing');
 assert((await text('#detail-content')).includes('未找到任务')&&!(await text('#detail-content')).includes('库存归档'),'Unknown task does not leak stale detail');
 await go('detail/task_finance');
 assert((await text('#detail-content')).includes('尚未配置完成'),'Draft has a dedicated empty state');
 await go('home');await input('#instance-search','does-not-exist');
 assert((await text('#instance-rows')).includes('没有匹配'),'Instance search empty state');
 await input('#instance-search','');
 await click('#theme-toggle');assert(await evaluate('!document.body.classList.contains("dark")'),'Light theme activates');
 await screen('home-light');
 await click('#theme-toggle');
 await screen('home-narrow',700,1000);
 assert(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'700px home has no document overflow');
 await go('detail/task_orders_prod');await screen('detail-mobile',390,844);
 assert(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'390px detail has no document overflow');
 assert(await evaluate('getComputedStyle(document.querySelector("#detail-inspector")).display!=="none"'),'Mobile detail keeps source configuration accessible');
 await click('#menu');assert(await evaluate('document.querySelector("#sidebar").classList.contains("open")'),'Mobile navigation opens');
 await click('.nav[data-page="add"]');await pause(100);
 assert(await evaluate('!document.querySelector("#sidebar").classList.contains("open")'),'Mobile navigation closes after routing');
 await screen('add-mobile',390,844);
 assert(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'390px add page has no document overflow');
 await click('.map-check[value="payments"]');
 assert((await text('#count'))==='3'&&(await text('#add-target-tables')).includes('payments'),'Add preview maps selected source tables');
 await go('settings');await screen('settings',1440,1024);
 await go('home');await click('#logout');
 assert(await evaluate('document.querySelector("#app").classList.contains("hidden")'),'Logout hides business pages');
 await go('detail/task_orders_prod');
 assert(await evaluate('document.querySelector("#app").classList.contains("hidden")'),'Signed-out hash navigation remains guarded');
 assert(errors.length===0,'No browser script or resource errors');
 await writeFile(join(out,'results.json'),JSON.stringify({checks,errors},null,2));
 console.log(JSON.stringify({passed:checks.length,errors,screenshots:out},null,2));
}catch(error){
 await writeFile(join(out,'results.json'),JSON.stringify({checks,errors,failure:String(error)},null,2));
 console.error(error);process.exitCode=1;
}finally{
 if(ws)ws.close();chrome.kill();await pause(600);await rm(profile,{recursive:true,force:true,maxRetries:4,retryDelay:300}).catch(()=>{});
}
