-- Connect to CDC_test on 192.168.0.10:54321 as postgres.
-- Creates only the demonstration table/publication; no replication slot yet.
CREATE TABLE IF NOT EXISTS public.cdc_pg15_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    amount NUMERIC(24,6),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB,
    changed_at TIMESTAMPTZ(6) NOT NULL DEFAULT now()
);
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'cdc_pg15_demo') THEN
        CREATE PUBLICATION cdc_pg15_demo FOR TABLE public.cdc_pg15_demo;
    END IF;
END
$$;
